### ISSUE TITLE
User edit: In role edit dialog, persist updates on confirm 

### ISSUE THREAD

**Issue by minotogna** [openforis/fra-platform#1520]
- [x] implement auto save for all user properties
- [x] Remove buttons 
- [ ] Auto save user roles 
- [ ] Move admin checkbox at the end of the form with window.alert confirmation 

OJ: When editing users, adding countries for reviewer or collaborator admin have to save twice, should only need to save once

**Comment by rfontanarosa** [comment]
unfortunately it's not that easy and it needs to be discussed because the whole form behaviour needed to be changed.

at the moment the form is not saved twice, when an administrator change the country permissions of a reviewer or a collaborator, this changed is applied (button Apply) but not persisted.

<img width="885" alt="Schermata 2022-09-19 alle 12 40 52" src="https://user-images.githubusercontent.com/10047945/191002553-49f32c97-d317-45a8-9f06-6fa64d3a4ec6.png">

<img width="682" alt="Schermata 2022-09-19 alle 12 56 31" src="https://user-images.githubusercontent.com/10047945/191002656-48234df5-a148-4227-8426-de7278170b04.png">
