### ISSUE TITLE
Data edit: Could not serve - deadlock detected

### ISSUE THREAD

**Issue by minotogna** [openforis/fra-platform#1735]
when editing fast two different nodes, server gives error deadlock detected.
tested with Fin 2025 (see video)

https://user-images.githubusercontent.com/1138156/203285952-913849b5-a23c-4781-9b5d-1f20bf4000c3.mov

**Comment by rfontanarosa** [comment]
we found two solutions, both of them have a side effect that should be fixed (see video below).

**Solution 1**: use  `await client.func('pg_advisory_xact_lock', [1])`
this is a transaction-level lock identified by 1, this means that if another transaction with the same id will wait its turn

**Solution 2**: instead of send a (debounced) request for every cell change, collect them into a queue which is already supported but not implemented

**Side-effect**: when two values are modified, if they are dependant by each other, before the second request is completed the second input returns to its original value

https://user-images.githubusercontent.com/10047945/203769135-b2ef8eb0-ce19-47b4-9e90-e0d0e8c27baa.mov
