### ISSUE TITLE
AutoCompleteInput - Value MUST be selected from the list

### ISSUE THREAD

**Issue by rfontanarosa** [openforis/fra-platform#2565]
Value which matches with the search string is not automatically selected. It must be selected from the list to make it effective. This is confusing.

Bug found by Chiara Patriarca

https://user-images.githubusercontent.com/10047945/234279715-201370ae-1a71-4d6b-ab32-e86ddf8afa40.mov

**Comment by sorja** [comment]
So allow free edit/free text input or change to normal select?
@rfontanarosa

**Comment by minotogna** [comment]
> So allow free edit/free text input or change to normal select?
> 
> @rfontanarosa 

@rfontanarosa @sorja the fact that the value is not selected on blur out is expected.

I'm proposing the following update:
- [x] On click outside options dialog/text input and if there's text then: select the option if its value is equal to text input , otherwise the text input value must be reset and no option is selected .

Would that work ?

**Comment by sorja** [comment]
Sounds good
