### ISSUE TITLE
Urgent - table 1b …of which primary forest / …of which introduced cannot be zero

### ISSUE THREAD

**Issue by pengchenglai** [openforis/fra-platform#3198]
@sorja @minotogna 

**Describe the bug**
table 1b …of which primary forest / …of which introduced cannot be zero when all the percentages assinged for national classes are empty(see below the screenshot).

**To Reproduce**
1. Go to 'Bangladesh'- tab 1b
2. Click on 'year 2000' for example
3. See error

**Expected behavior**
If all the percentages assinged for national classes are empty , the sum of area for **…of which primary forest** / **…of which introduced species** should be empty.

**Screenshots**
![image](https://github.com/openforis/fra-platform/assets/99216009/055d7785-9e6b-4aa9-bddb-4e4b23bf3f90)
![image](https://github.com/openforis/fra-platform/assets/99216009/c6612acc-91ef-491e-bacb-0c06419726e9)

**Comment by sorja** [comment]
@pengchenglai @minotogna 
So, this is because of the rule conflict

Can you advice? Probably if any value for naturally regenerating forest > 0, we ignore 0?


Current situation:
![image](https://github.com/openforis/fra-platform/assets/5508251/0ff2bb84-1d9e-4f77-a59f-5f4adc215632)

Previously requested rules:
- If we have all zeroes, will should show 0:
![image](https://github.com/openforis/fra-platform/assets/5508251/39ffce7a-4a47-4d28-a262-049268ab75b5)

- If no values given, show dash (empty)
![image](https://github.com/openforis/fra-platform/assets/5508251/d9c035b4-2c5c-4a64-8ca3-d49ada607ae5)

- **If any value given, show total**
![image](https://github.com/openforis/fra-platform/assets/5508251/670db44e-bf2c-41c6-acc2-783bbcb227e7)

So current behavior is a conflict of rules:
![image](https://github.com/openforis/fra-platform/assets/5508251/92ffecc8-1523-4127-af3d-07096421043c)

- Because `Rubber Plantation` and `Rubber Plantation` have a value of `0.00%` we have given (a hidden) value of 0. Because we show the total value if _any value exists_ , then total is shown.


------------


**!! In the modified local version of the code !!** (ONLY FOR SCREENSHOT PURPOSE!)

We can render the zero values to get an explanation why the total is 0.
These highlighted values are hidden in the normal version of the code (as requested)

![image](https://github.com/openforis/fra-platform/assets/5508251/c1e56df5-61c8-48a5-a08c-ae9daf6f168d)


Hope this explains the current situation

Please advice on how to change the rule set for ODP or if the suggested (any value for naturally renegerating forest is > 0 ?) is ok

**Comment by pengchenglai** [comment]
@sorja 

I see the point as there is no rule applied for this situation, but only for all zeros in the parent class.

Plz add an extra condition(rule) for calculating the total of **…of which primary forest**(for instance): if the area of any one of the national classes of the parent(in this case **Naturally regenerating forest**) is >0 % and the percentages for child class( …of which primary forest) are **all empty**, the **Total** should **be empty**. Thank you!

![image](https://github.com/openforis/fra-platform/assets/99216009/d1fa6900-bc9d-4ced-8791-b44476c7b934)

PS(do not need to change as it is good currently):
Just FYR: if the area of any one of the national classes of the parent(in this case **Naturally regenerating forest**) is >0 % and the percentages for child class( …of which primary forest) are **not ** all empty, the **Total** should **the sum of all available values **.
![image](https://github.com/openforis/fra-platform/assets/99216009/800e2a1f-2763-4677-85d5-a024c21e0af8)

**Comment by pengchenglai** [comment]
@sorja 

Not possible to remove 0s in the second table **Primary forest by climatic domain** for Bangladesh.
![image](https://github.com/openforis/fra-platform/assets/99216009/f8a7408f-86d1-4a97-97b6-bd1a9a8b9f8e)

**Comment by minotogna** [comment]
@pengchenglai please , talk to ÖJ
We have received different instructions

**Comment by pengchenglai** [comment]
> if any value for naturally regenerating forest > 0, we ignore 0(in the _naturally regenerating forest)_?

@sorja 
I agree and will send you an email by Örjan tomorrow.
