### ISSUE TITLE
NDP: References -> Upload and select file from Links&Repository

### ISSUE THREAD

**Issue by sorja** [openforis/fra-platform#3211]
** Allow users to select and upload files from Links (available in Links & Repository section)**

**Comment by minotogna** [comment]
@sorja we need also to:

- [x] Update Country Repository access:
    - By default all country repository files are **always private**

- [x] When selecting a file in the NDP Reference dialog a file must become publicly available when assessment/cycle is published

- [x] In the NDP Reference Repository File Selector Dialog add a sentence on top: `A file added as reference will become automatically publicly accessible`

- [ ] ~~In the Country repository list, add a column 'Public' with Checkbox to Toggle Switch that updates the access permission (question: should we add headers to the table?)~~

- [x] Delete file BE validation: when deleting a file, check if in database the link is used in any description / NDP reference. if yes throw error to client saying : `File cannot be deleted because used in sections: {list the sections}` 

- [x] In NDP Reference Dialog, relablel 'Close' to 'Apply'

- [x] In NDP Reference, before button 'Repository' add icon file 


```svg
<symbol id="icon-files" viewBox="0 0 24 24">
<path d="M5 0v3h-3v21h17v-3h3v-21h-17zM17 22h-13v-17h1v16h12v1zM20 19h-13v-17h13v17zM15 5h-6v2h6v-2zM18 8h-9v1h9v-1zM18 10h-9v1h9v-1zM18 12h-9v1h9v-1zM12 14h-3v1h3v-1z"></path>
</symbol>
```

**Comment by sorja** [comment]
- [x] Rename `private` to `props.hidden`
- [x] Disable button when request is pending (delete)

**Comment by minotogna** [comment]
@sorja for this PR TODO:

- [x] When uploading a file through NDP references Drag & Drop access must be private
- [x] Only when selecting and clicking 'apply' call BE endpoint to make access public 
- [x] IN NDP References Dialog comment out 'All' button 
- [x] in NDP Reference dialog, when clicking on file name, it downloads the file and select it at the same time. -> Do not allow download , allow select file only 
- [x] NDP Reference Dialog: There's no way to close the dialog without clicking apply.
  - add cancel button (white) on the left side of apply
