### ISSUE TITLE
Language redirection issue for FAQ

### ISSUE THREAD

**Issue by pengchenglai** [openforis/fra-platform#3518]
**Describe the bug**
For all six languages, it seems after tab 3a, click FAQ cannot be correctly redirected to the corresponding place.

**To Reproduce**
1. Go to Any country
2. Click on, for example, table 3b - FAQ
3. The new window of FAQ pops up with the list of table names showing on the top

**Expected behavior**
Correct redirection

**Screenshots**
![image](https://github.com/openforis/fra-platform/assets/99216009/a4e25c7a-ed2c-4b3b-aa50-fdeb9e4eb0ad)

**Comment by pengchenglai** [comment]
@minotogna

**Comment by yaguzmang** [comment]
Hi @pengchenglai. The scroll for 1d, 2d, 3b and others, fails because there is no corresponding FAQ section for them. For example, 3b missing:

<img src="https://github.com/openforis/fra-platform/assets/41337901/ee1df7c0-3521-425e-b153-4b4191e79e5d" width="250" height="400" />


What would the expected behavior be in that case?

**Comment by pengchenglai** [comment]
@yaguzmang 

Then plz remove the FAQ tabs for these sessions if there are no corresponding content for it.
![image](https://github.com/openforis/fra-platform/assets/99216009/afc04805-eae5-4b55-ba03-d53b3d36699c)

**Comment by yaguzmang** [comment]
@minotogna To avoid hardcoding the available anchors for the FAQ, I am thinking of adding a new endpoint that returns the available anchors of a Definitions file given assessment, cycle, language, etc. Any thoughts on that?

**Comment by minotogna** [comment]
@yaguzmang this should be handled through table metadata. ping me on slack when you're there
