### ISSUE TITLE
High priority - table layout -> CAF - Forest growing stock composition - Comments

### ISSUE THREAD

**Issue by pengchenglai** [openforis/fra-platform#3714]
@minotogna 

**Is your feature request related to a problem? Please describe.**
Once clicking done, the layout of the table may be corrupted(example see below):
![MicrosoftTeams-image (4)](https://github.com/openforis/fra-platform/assets/99216009/a7e0d943-8c79-4303-8703-a931e816e10b)
![MicrosoftTeams-image (5)](https://github.com/openforis/fra-platform/assets/99216009/516b88cc-9304-4c84-a07f-ccb79dc74f2e)

**Describe the solution you'd like**
If a user has arranged the layout of a table and clicked the done tab, the table layout should remain more or less the same.

**Describe alternatives you've considered**
At least, the situation of one word(number) cut off into two lines would be avoided.

**Comment by minotogna** [comment]
@pengchenglai we can't control what user is copying . 
I don't even know why we want to allow to paste structured data in a non structured field .
If user doesn't use the table provided by the editor , we can't do anything about that .

**Comment by pengchenglai** [comment]
@minotogna 

The reason behind this could be:
Countries may already have the original table information prepared before reporting it to the platform, and it is not easy to move all the text from the prepared table to the new tables provided by the editor if there is a lot of data.

**Comment by minotogna** [comment]
@pengchenglai that is user generated content. The table that the user has inserted has a static width of 192px.
Someone should manually fix the table, that is not a code issue, but content issue.
If you really want, I can edit the content, and afterwards I will remove my activity recorded in the database so that it won't appear in the Recent activity section that I edited it.

<img width="1789" alt="image" src="https://github.com/openforis/fra-platform/assets/1138156/914aa37c-e52c-4c9b-a95c-28ecf586613c">

**Comment by minotogna** [comment]
It will look like this @pengchenglai : 

<img width="1800" alt="Screenshot 2024-04-10 at 11 07 51" src="https://github.com/openforis/fra-platform/assets/1138156/872c63a8-e1d0-4e5b-b9eb-89d13fb14c2e">

**Comment by pengchenglai** [comment]
@minotogna 

Great, thank you! Just one question: How could the user know which width is good if they do not inspect the code(that is the common case)? 

What they usually do is copy & paste tables from excel and if the layout does not look good, then users normally stretch the table to the extent until it looks fine when the editing box is open, but in some cases, the table layout could be corrupted when done the editing, as what happened above.

**Comment by minotogna** [comment]
> @minotogna
> 
> Great, thank you! Just one question: How could the user know which width is good if they do not inspect the code(that is the common case)?
> 
> What they usually do is copy & paste tables from excel and if the layout does not look good, then users normally stretch the table to the extent until it looks fine when the editing box is open, but in some cases, the table layout could be corrupted when done the editing, as what happened above.

@pengchenglai users cannot know how to do that. (usually).
The problem is not word, not excel, not html, the problem is:

we allow to paste data from external software like excel and word that have proprietary format into html content.
We and every person in the world has no control over the result and it might look different from the original content, blaming the target software , like in this case the Platform.

If we will continue allow this, we will continue to face these issues. very simple.

The ideal solution would be to allow uploading files if we want to allow word, excel etc...
the responsibility of those fields are user responsibility, not the Platform .

**Comment by minotogna** [comment]
@pengchenglai I have manually updated the content in production
